spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:6767/orderdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
